default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_TEST") { ENV.fetch("DATABASE_URL").sub(/\/([^\/\?]+)(\?|$)/, "/forecast_test\\2") } %>

production:
  primary: &primary_production
    <<: *default
    database: forecast_production
    username: forecast
    password: <%= ENV["FORECAST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: forecast_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: forecast_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: forecast_production_cable
    migrations_paths: db/cable_migrate
